# Generated by Django 5.2.16 on 2026-08-06 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
