# Generated by Django 5.2.16 on 2026-08-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('suspended', 'Suspended'), ('banned', 'Permanently Banned'), ('deleted', 'Soft Deleted')], default='unverified', max_length=20),
        ),
    ]
