#!/usr/bin/env bash
set -e

gh issue create --title "Day 6 — Repo skeleton + OAuth app registration" --body-file "issues/day-06-repo-skeleton-oauth-app-registration.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 7 — Custom user model" --body-file "issues/day-07-custom-user-model.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 8 — Full Docker Compose" --body-file "issues/day-08-full-docker-compose.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 9 — Redis session backend" --body-file "issues/day-09-redis-session-backend.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 10 — DRF baseline + React skeleton" --body-file "issues/day-10-drf-baseline-react-skeleton.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 11 — django-allauth headless" --body-file "issues/day-11-django-allauth-headless.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 12 — Buffer + confirm the sessions/Redis ADR" --body-file "issues/day-12-buffer-confirm-the-sessionsredis-adr.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 13 — Celery pipeline" --body-file "issues/day-13-celery-pipeline.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 14 — Signup (backend + form)" --body-file "issues/day-14-signup-backend-form.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 15 — Email verification" --body-file "issues/day-15-email-verification.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 16 — Login" --body-file "issues/day-16-login.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 17 — Password reset" --body-file "issues/day-17-password-reset.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 18 — Logout" --body-file "issues/day-18-logout.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 19 — Buffer + confirm the async/SMTP ADR" --body-file "issues/day-19-buffer-confirm-the-asyncsmtp-adr.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 20 — Real SMTP" --body-file "issues/day-20-real-smtp.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 21 — CORS" --body-file "issues/day-21-cors.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 22 — Google OAuth" --body-file "issues/day-22-google-oauth.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 23 — GitHub OAuth" --body-file "issues/day-23-github-oauth.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 24 — OAuth email collision" --body-file "issues/day-24-oauth-email-collision.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 25 — OAuth error states" --body-file "issues/day-25-oauth-error-states.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 26 — Buffer + write the OAuth-quirks ADR" --body-file "issues/day-26-buffer-write-the-oauth-quirks-adr.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 27 — Cloudflare + Caddy" --body-file "issues/day-27-cloudflare-caddy.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 28 — Production Dockerfile" --body-file "issues/day-28-production-dockerfile.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 29 — docker-compose.prod.yml" --body-file "issues/day-29-docker-composeprodyml.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 30 — /api/auth/me + React Query" --body-file "issues/day-30-apiauthme-react-query.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 31 — Tier 1 close" --body-file "issues/day-31-tier-1-close.md" --label "tier-1" --milestone "Tier 1 — 90%"
gh issue create --title "Day 32 — Rate-limiting design" --body-file "issues/day-32-rate-limiting-design.md" --label "tier-2" --milestone "Tier 2 — 95%"
gh issue create --title "Day 33 — Rate limiting live + Turnstile (full-time) + 429 UI" --body-file "issues/day-33-rate-limiting-live-turnstile-full-time-429-ui.md" --label "tier-2" --milestone "Tier 2 — 95%"
gh issue create --title "Day 34 — GitHub private-email quirk" --body-file "issues/day-34-github-private-email-quirk.md" --label "tier-2" --milestone "Tier 2 — 95%"
gh issue create --title "Day 35 — Ghost-session fix" --body-file "issues/day-35-ghost-session-fix.md" --label "tier-2" --milestone "Tier 2 — 95%"
gh issue create --title "Day 36 — Concurrent sessions + read-only list" --body-file "issues/day-36-concurrent-sessions-read-only-list.md" --label "tier-2" --milestone "Tier 2 — 95%"
gh issue create --title "Day 37 — Resend cooldown UX" --body-file "issues/day-37-resend-cooldown-ux.md" --label "tier-2" --milestone "Tier 2 — 95%"
gh issue create --title "Day 38 — OAuth disconnect/unlink" --body-file "issues/day-38-oauth-disconnectunlink.md" --label "tier-2" --milestone "Tier 2 — 95%"
gh issue create --title "Day 39 — Test suite: happy paths" --body-file "issues/day-39-test-suite-happy-paths.md" --label "tier-2" --milestone "Tier 2 — 95%"
gh issue create --title "Day 40 — Test suite: failure paths" --body-file "issues/day-40-test-suite-failure-paths.md" --label "tier-2" --milestone "Tier 2 — 95%"
gh issue create --title "Day 41 — Test suite: session behavior" --body-file "issues/day-41-test-suite-session-behavior.md" --label "tier-2" --milestone "Tier 2 — 95%"
gh issue create --title "Day 42 — Tier 2 close: CI" --body-file "issues/day-42-tier-2-close-ci.md" --label "tier-2" --milestone "Tier 2 — 95%"
gh issue create --title "Day 43 — Timing harness" --body-file "issues/day-43-timing-harness.md" --label "tier-3" --milestone "Tier 3 — 96%"
gh issue create --title "Day 44 — Fix leaks" --body-file "issues/day-44-fix-leaks.md" --label "tier-3" --milestone "Tier 3 — 96%"
gh issue create --title "Day 45 — Breach password check" --body-file "issues/day-45-breach-password-check.md" --label "tier-3" --milestone "Tier 3 — 96%"
gh issue create --title "Day 46 — CORS edge cases" --body-file "issues/day-46-cors-edge-cases.md" --label "tier-3" --milestone "Tier 3 — 96%"
gh issue create --title "Day 47 — Re-auth for sensitive actions" --body-file "issues/day-47-re-auth-for-sensitive-actions.md" --label "tier-3" --milestone "Tier 3 — 96%"
gh issue create --title "Day 48 — MFA (TOTP)" --body-file "issues/day-48-mfa-totp.md" --label "tier-3" --milestone "Tier 3 — 96%"
gh issue create --title "Day 49 — Session revoke actions" --body-file "issues/day-49-session-revoke-actions.md" --label "tier-3" --milestone "Tier 3 — 96%"
gh issue create --title "Day 50 — Tier 3 close" --body-file "issues/day-50-tier-3-close.md" --label "tier-3" --milestone "Tier 3 — 96%"
gh issue create --title "Day 51 — Kill Redis on purpose" --body-file "issues/day-51-kill-redis-on-purpose.md" --label "tier-4" --milestone "Tier 4 — 97%"
gh issue create --title "Day 52 — Redis pool tuning" --body-file "issues/day-52-redis-pool-tuning.md" --label "tier-4" --milestone "Tier 4 — 97%"
gh issue create --title "Day 53 — Structured logging" --body-file "issues/day-53-structured-logging.md" --label "tier-4" --milestone "Tier 4 — 97%"
gh issue create --title "Day 54 — OWASP ASVS audit" --body-file "issues/day-54-owasp-asvs-audit.md" --label "tier-4" --milestone "Tier 4 — 97%"
gh issue create --title "Day 55 — Fix ASVS gaps" --body-file "issues/day-55-fix-asvs-gaps.md" --label "tier-4" --milestone "Tier 4 — 97%"
gh issue create --title "Day 56 — MFA recovery edge cases" --body-file "issues/day-56-mfa-recovery-edge-cases.md" --label "tier-4" --milestone "Tier 4 — 97%"
gh issue create --title "Day 57 — Health checks" --body-file "issues/day-57-health-checks.md" --label "tier-4" --milestone "Tier 4 — 97%"
gh issue create --title "Day 58 — Tier 4 close" --body-file "issues/day-58-tier-4-close.md" --label "tier-4" --milestone "Tier 4 — 97%"
gh issue create --title "Day 59 — Hunt races" --body-file "issues/day-59-hunt-races.md" --label "tier-5" --milestone "Tier 5 — 98%"
gh issue create --title "Day 60 — Fix races" --body-file "issues/day-60-fix-races.md" --label "tier-5" --milestone "Tier 5 — 98%"
gh issue create --title "Day 61 — Locust setup" --body-file "issues/day-61-locust-setup.md" --label "tier-5" --milestone "Tier 5 — 98%"
gh issue create --title "Day 62 — Run + find the bottleneck" --body-file "issues/day-62-run-find-the-bottleneck.md" --label "tier-5" --milestone "Tier 5 — 98%"
gh issue create --title "Day 63 — Fix the bottleneck" --body-file "issues/day-63-fix-the-bottleneck.md" --label "tier-5" --milestone "Tier 5 — 98%"
gh issue create --title "Day 64 — Finalize the threat model" --body-file "issues/day-64-finalize-the-threat-model.md" --label "tier-5" --milestone "Tier 5 — 98%"
gh issue create --title "Day 65 — Implementation close" --body-file "issues/day-65-implementation-close.md" --label "tier-5" --milestone "Tier 5 — 98%"
gh issue create --title "Day 66 — Real second use" --body-file "issues/day-66-real-second-use.md" --label "final-polish" --milestone "Final Polish"
gh issue create --title "Day 67 — Fix what Day 66 found + changelog" --body-file "issues/day-67-fix-what-day-66-found-changelog.md" --label "final-polish" --milestone "Final Polish"
gh issue create --title "Day 68 — External eyes" --body-file "issues/day-68-external-eyes.md" --label "final-polish" --milestone "Final Polish"
gh issue create --title "Day 69 — Address the highest-value feedback" --body-file "issues/day-69-address-the-highest-value-feedback.md" --label "final-polish" --milestone "Final Polish"
gh issue create --title "Day 70 — Announcement + retrospective" --body-file "issues/day-70-announcement-retrospective.md" --label "final-polish" --milestone "Final Polish"
