"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent #Goes three levels deep. 

#Initialize environ and set type defaults.
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, True),
    ALLOWED_HOSTS=(list, [])
)

#Read the .env from your base directory
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production! 
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', 
    default=['localhost', '127.0.0.1', '[::1]', 'host.docker.internal', 'django']
)  # Split the comma-separated list of allowed hosts


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for django-allauth
]

SITE_ID = 1  # Required for django-allauth

THIRD_PARTY_APPS = [
    # Add your third-party apps here
    "rest_framework",
    "allauth", 
    "allauth.account",
    "allauth.headless"
]

LOCAL_APPS = [
    # Add your local apps here
    "user_auth",
    "core",
]

#Combine local apps, third party apps and django apps into one list of installed apps.
# Works like a charm for production.
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS  


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB'),          # Your database name
        'USER': env('POSTGRES_USER'),              # Your database username
        'PASSWORD': env('POSTGRES_PASSWORD'),      # Your database password
        'HOST': env('POSTGRES_HOST'),             # Use localhost or server IP
        'PORT': env('POSTGRES_PORT'),                  # Default PostgreSQL port
    }
}

# CACHE: 
CACHES = {
    "default":{
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env('REDIS_URL'),  # Redis service name from the compose.yml file.
        
        # Only change this if Django itself manages the routing.
        # To ShardClient if you have sharded Redis setup.
        # To SentinelClient if you have a Redis Sentinel setup for HA.
        "OPTIONS":{
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'user_auth.User'  # Specify the custom user model

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 15,  # Enforce a minimum password length of 15
        }
    },
    {
        'NAME': 'core.validators.MaximumLengthValidator',  # Custom validator for maximum length
        'OPTIONS': {
            'max_length': 64,  # Enforce a maximum password length of 64
            }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Handling session cookies via cache like this:
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'  # Use the default cache for session storage

SESSION_COOKIE_HTTPONLY = True  # Mitigates the risk of client-side script accessing the session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # Helps prevent CSRF attacks
SESSION_COOKIE_SECURE = False  # Set to True in production when using HTTPS

SESSION_COOKIE_AGE = 1209600  # Two weeks, in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session will expire when the user closes their browser
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

"""
# DRF baseline
# Default-locked posture: every endpoint requires auth unless explicitly opened up
# with permission_classes = [AllowAny] on that view. Safer failure mode for an
# auth boilerplate — better to accidentally lock something down than accidentally
# expose it.
"""
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# django-allauth: headless mode
# No Django-rendered templates for auth — allauth exposes JSON endpoints,
# React consumes them directly. Older allauth tutorials assume the
# template-rendering mode; don't copy config from those blindly.
HEADLESS_ONLY = True
HEADLESS_CLIENTS = ["browser"]  # Browser endpoints.

# Email for sign up not username.
ACCOUNT_SIGNUP_FIELDS = ["email*"]

#Remove password verification for signup.
ACCOUNT_SIGNUP_PASSWORD_VERIFICATION = False  
# This is an extra field.
ACCOUNT_SIGNUP_FORM_CLASS = "core.forms.HeadlessExtraSignupForm"  # Custom signup form for extra fields

# No username
ACCOUNT_USER_MODEL_USERNAME_FIELD = None #No username needed.

ACCOUNT_LOGIN_METHODS = {"email"}  # Use email for login

ACCOUNT_ADAPTER = "core.adapters.AccountAdapter"
# Mandatory verification, paired deliberately with enumeration prevention below —
# ACCOUNT_PREVENT_ENUMERATION alone does not close the enumeration hole; it needs
# mandatory verification to actually be meaningful (signup response can't leak
# whether an email already exists if every signup gets the identical
# "check your email" response regardless).
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_PREVENT_ENUMERATION = True

# Celery configuration and the settings needed for it to work with Django.
CELERY_BROKER_URL = env('CELERY_BROKER_URL')  # Separate this from the Redis URL used for app caching or sessions data.
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC' 